root: true
parser: "@typescript-eslint/parser"

plugins:
  - "@typescript-eslint"
  - prettier

extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier/@typescript-eslint"

rules:
  "prettier/prettier": "error"
  "@typescript-eslint/camelcase": "off"
  "@typescript-eslint/no-explicit-any": "error"
  "@typescript-eslint/explicit-function-return-type": "warn"

parserOptions:
  ecmaVersion: 2019

env:
  browser: true
  node: true
  jest: true
  es6: true
