extends:
  - plugin:@lichtblick/base
  - plugin:@lichtblick/jest

env:
  node: true

ignorePatterns:
  - dist

overrides:
  - files: ["*.ts", "*.tsx"]
    extends:
      - plugin:@lichtblick/typescript
    parserOptions:
      project: tsconfig.json
    rules:
      "@typescript-eslint/no-empty-function": off
      "@typescript-eslint/no-unsafe-member-access": off
      "@typescript-eslint/restrict-template-expressions": [error, { allowAny: true }]
